channels:
   - conda-forge
   - bioconda
   - defaults
dependencies:
   - snakemake-minimal=7.6.1
   - sra-tools=2.9.6
   - bbmap=38.96
   - conda-forge::python=3.7
   - conda-forge::scikit-learn=0.23.2
   - conda-forge::numpy=1.19.5
   - conda-forge::pandas=0.23.4
   - conda-forge::seaborn=0.11.1
   - conda-forge::umap-learn=0.4.2
   - conda-forge::numba=0.50.1
   - conda-forge::scipy=1.3.0
   - conda-forge::plotnine=0.5.1
   - conda-forge::libiconv=1.15
   - pip=19.2.1
   - pip:
     - git+https://github.com/greenelab/generic-expression-patterns@master
     - matplotlib==3.0.0
     - ponyo==0.6.1
     - matplotlib-venn
     - svgutils==0.3.1
